# Generated by Django 5.0.3 on 2024-10-12 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('WSSGTemplate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guild', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('entries', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraMessage', models.CharField(default='test', max_length=1000)),
                ('message', models.JSONField(default=list)),
                ('identifier', models.CharField(default='test', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TestPos',
            fields=[
                ('uid', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, unique=True)),
                ('playerClass', models.CharField(default='', max_length=1000)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='guild_members', to='WSSGTemplate.guild')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishSelecting', models.JSONField(default=list)),
                ('isActive', models.BooleanField(default=True)),
                ('startGame', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='WSSGTemplate.player')),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='lobby_winner', to='WSSGTemplate.player')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.JSONField(default=list)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WSSGTemplate.player',
                                               to_field='user')),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_guild_backref',
                                       to='WSSGTemplate.player'),
        ),
        migrations.AddField(
            model_name='guild',
            name='players',
            field=models.ManyToManyField(related_name='guilds', to='WSSGTemplate.player'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('personOne', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='friendships_as_person_one', to='WSSGTemplate.player')),
                ('personTwo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='friendships_as_person_two', to='WSSGTemplate.player')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='received_friend_requests', to='WSSGTemplate.player')),
                ('requestor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='sent_friend_requests', to='WSSGTemplate.player')),
            ],
        ),
        migrations.CreateModel(
            name='TTTGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.JSONField(default=['', '', '', '', '', '', '', '', ''])),
                ('current_index', models.IntegerField(default=0)),
                ('host', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='game_host', to='WSSGTemplate.player')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WSSGTemplate.lobby')),
                ('opponent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='game_opponent', to='WSSGTemplate.player')),
            ],
        ),
    ]
