# Generated by Django 5.0.3 on 2024-10-12 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0002_initial'),
    ]

    operations = [
    ]
