# Generated by Django 5.0.3 on 2024-10-12 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0003_auto_20241013_0057'),
    ]

    operations = [
    ]
