# Generated by Django 4.2.7 on 2023-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0003_testpos_delete_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpos',
            name='id',
        ),
        migrations.AlterField(
            model_name='testpos',
            name='uid',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
