# Generated by Django 4.2.7 on 2023-11-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0004_remove_testpos_id_alter_testpos_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpos',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testpos',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testpos',
            name='z',
            field=models.FloatField(default=0.0),
        ),
    ]
