# Generated by Django 5.0.3 on 2024-10-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0004_auto_20241013_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
