# Generated by Django 4.2.7 on 2023-11-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WSSGTemplate', '0005_alter_testpos_x_alter_testpos_y_alter_testpos_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('generic_id', models.AutoField(primary_key=True, serialize=False)),
                ('requestor', models.IntegerField(default=-1)),
                ('receiver', models.IntegerField(default=-1)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('generic_id', models.AutoField(primary_key=True, serialize=False)),
                ('personOne', models.IntegerField(default=-1)),
                ('personTwo', models.IntegerField(default=-1)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('generic_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_id', models.CharField(default='', max_length=50, unique=True)),
                ('inventory', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('generic_id', models.AutoField(primary_key=True, serialize=False)),
                ('lobby_id', models.CharField(default='1', max_length=50)),
                ('lobby_players', models.JSONField(default=list)),
                ('finish_selecting', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000, unique=True)),
                ('player_class', models.CharField(default='', max_length=1000)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
