# Generated by Django 4.2.7 on 2023-11-26 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0006_friendrequest_friendship_inventory_lobby_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='id',
            new_name='generic_id',
        ),
    ]
