# Generated by Django 4.2.7 on 2023-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0007_rename_id_player_generic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='generic_id',
            new_name='genericID',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='generic_id',
            new_name='genericID',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='generic_id',
            new_name='genericID',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inventory_id',
            new_name='inventoryID',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='finish_selecting',
            new_name='finishSelecting',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='generic_id',
            new_name='genericID',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='lobby_id',
            new_name='lobbyID',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='lobby_players',
            new_name='lobbyPlayers',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='generic_id',
            new_name='genericID',
        ),
    ]
