# Generated by Django 4.2.7 on 2023-11-26 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0008_rename_generic_id_friendrequest_genericid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_class',
            new_name='playerClass',
        ),
    ]
