# Generated by Django 4.2.7 on 2024-03-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WSSGTemplate', '0009_rename_player_class_player_playerclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='finishSelecting',
            new_name='finish_selecting',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='personOne',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='personTwo',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inventoryID',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='lobbyPlayers',
        ),
        migrations.AddField(
            model_name='friendship',
            name='person_one',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='friendships_as_person_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='person_two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='friendships_as_person_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='WSSGTemplate.player'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(to='WSSGTemplate.player'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='received_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('guildName', models.CharField(default='guild', max_length=1000)),
                ('guildOwner',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_guild_backref',
                                      to='WSSGTemplate.player')),
                ('guildPlayers', models.ManyToManyField(related_name='guilds', to='WSSGTemplate.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='guild_members', to='WSSGTemplate.guild'),
        ),
    ]
