# Generated by Django 4.2.7 on 2024-03-02 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0010_rename_finishselecting_lobby_finish_selecting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='person_one',
            new_name='personOne',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='person_two',
            new_name='personTwo',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='finish_selecting',
            new_name='finishSelecting',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='is_active',
            new_name='isActive',
        ),
    ]
