# Generated by Django 4.2.7 on 2024-03-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0011_rename_person_one_friendship_personone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='received_friend_requests', to='WSSGTemplate.player'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sent_friend_requests', to='WSSGTemplate.player'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='personOne',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='friendships_as_person_one', to='WSSGTemplate.player'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='personTwo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='friendships_as_person_two', to='WSSGTemplate.player'),
        ),
    ]
