# Generated by Django 4.2 on 2024-03-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0012_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTTLobbyRequest',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('lobbyHost', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='TTT_Host', to='WSSGTemplate.player')),
                ('lobbyOpponent',
                 models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='TTT_Opponent', to='WSSGTemplate.player')),
            ],
        ),
    ]
