# Generated by Django 4.2 on 2024-03-04 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0013_tttlobbyrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TTTLobbyRequest',
            new_name='TTTGameRequest',
        ),
    ]
