# Generated by Django 4.2.7 on 2024-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0014_rename_tttlobbyrequest_tttgamerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCommand',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='test', max_length=1000)),
                ('command', models.JSONField(default=list)),
                ('identifier', models.CharField(default='test', max_length=1000)),
            ],
        ),
    ]
