# Generated by Django 4.2.7 on 2024-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0016_servermessage_delete_servercommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('entries', models.ManyToManyField(to='WSSGTemplate.leaderboardentry')),
            ],
        ),
    ]
