# Generated by Django 4.2.7 on 2024-03-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0017_leaderboardentry_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='player_name',
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='WSSGTemplate.player'),
        ),
    ]
