# Generated by Django 4.2.7 on 2024-03-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0018_remove_leaderboardentry_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobby',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='lobby_winner', to='WSSGTemplate.player'),
        ),
    ]
