# Generated by Django 4.2.7 on 2024-03-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0019_leaderboard_category_lobby_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTTGame',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.JSONField(default=list)),
                ('lobbyHost', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='TTT_Host', to='WSSGTemplate.player')),
                ('lobbyOpponent',
                 models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='TTT_Opponent', to='WSSGTemplate.player')),
            ],
        ),
        migrations.DeleteModel(
            name='TTTGameRequest',
        ),
    ]
