# Generated by Django 4.2.7 on 2024-03-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0020_tttgame_delete_tttgamerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tttgame',
            name='lobbyHost',
        ),
        migrations.RemoveField(
            model_name='tttgame',
            name='lobbyOpponent',
        ),
        migrations.AddField(
            model_name='lobby',
            name='startGame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tttgame',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='game_host', to='WSSGTemplate.player'),
        ),
        migrations.AddField(
            model_name='tttgame',
            name='opponent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='game_opponent', to='WSSGTemplate.player'),
        ),
    ]
