# Generated by Django 4.2.7 on 2024-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0021_remove_tttgame_lobbyhost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttgame',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
    ]
