# Generated by Django 4.2.7 on 2024-03-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0022_tttgame_current_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tttgame',
            name='host',
        ),
        migrations.RemoveField(
            model_name='tttgame',
            name='opponent',
        ),
        migrations.AddField(
            model_name='tttgame',
            name='lobby',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='WSSGTemplate.lobby'),
        ),
    ]
