# Generated by Django 4.2.7 on 2024-03-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0023_remove_tttgame_host_remove_tttgame_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tttgame',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='game_host', to='WSSGTemplate.player'),
        ),
        migrations.AddField(
            model_name='tttgame',
            name='opponent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='game_opponent', to='WSSGTemplate.player'),
        ),
    ]
