# Generated by Django 4.2.7 on 2024-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0024_tttgame_host_tttgame_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tttgame',
            name='action',
            field=models.JSONField(default=['X', '', '', '', '', '', '', '', '']),
        ),
    ]
