# Generated by Django 4.2.7 on 2024-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0025_alter_tttgame_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='entries',
        ),
        migrations.AlterField(
            model_name='tttgame',
            name='action',
            field=models.JSONField(default=['', '', '', '', '', '', '', '', '']),
        ),
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='entries',
            field=models.JSONField(default=list),
        ),
    ]
