# Generated by Django 4.2.7 on 2024-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0026_remove_leaderboard_entries_alter_tttgame_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermessage',
            name='uwu',
            field=models.CharField(default='test', max_length=1000),
        ),
    ]
