# Generated by Django 4.2.7 on 2024-03-11 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0027_servermessage_uwu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermessage',
            name='uwu',
        ),
    ]
