# Generated by Django 5.0.3 on 2024-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WSSGTemplate', '0028_remove_servermessage_uwu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('genericID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('messages', models.JSONField(default=list)),
            ],
        ),
        migrations.RenameField(
            model_name='servermessage',
            old_name='username',
            new_name='extraMessage',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
